### ISSUE TITLE
Affinity 

### ISSUE THREAD

**Issue by dbelousoff** [mattiasflodin/reckless#1]
Hello, 

Is there option to set core affinity for worker thread?

**Comment by mattiasflodin** [comment]
No but it seems like a reasonable addition. Would a specific core index be sufficient, or would it need to be an affinity mask? The latter seems slightly more difficult to make platform-agnostic.

Perhaps it would be better to just offer access to the std::thread object and you could use native_handle to do whatever you like?

**Comment by dbelousoff** [comment]
I think best option would be to just add access to underlying std::thread,
so user can handle affinities himself. Would be great to see it!

**Comment by mattiasflodin** [comment]
Resolved in c623d55.
