### ISSUE TITLE
-pthread is missing

### ISSUE THREAD

**Issue by mader102** [mattiasflodin/reckless#10]
it looks like that you are missing a -pthread here: https://github.com/mattiasflodin/reckless#building
Also -lreckless looks wrong it must be -lasynclog, because your Makefile creates libasynclog.a.

**Comment by mattiasflodin** [comment]
Hi, sorry for not getting back earlier, I have had family issues to sort out and haven't been able to pay much attention here for a while.

You're right. Poor testing on my end. I changed the library name at some point and must have had the old .a file lying around so I never got any error.

I'll revisit the makefile and make extra sure that binaries can link to it properly.

**Comment by mattiasflodin** [comment]
Resolved in a6e62d8 and 99d6f0f.
