### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [mattiasflodin/reckless#13]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by mattiasflodin** [comment]
I will look into it, thanks. Pull requests are welcome. :wink:

**Comment by vermosen** [comment]
Hi,
I just added up [a PR](https://github.com/mattiasflodin/reckless/pull/29) for this one. 

As a suggestion, there could be a few improvements to be done on the cmake project to make it a little bit more standard:
- add an install step
- unless there is an issue to do so, I'd leave the linkage undetermined in the project such one can set the BUILD_SHARED_LIBS flag to control the linkage (subsequently, we could add the shared option in the conan recipe to control the flag). 
- the optimization flags and debugging info are added up automatically in cmake based on the CMAKE_BUILD_TYPE passed, so it shouldn't be needed to force them.

Let me know if you have questions.

**Comment by mattiasflodin** [comment]
Resolved in 3.0.1. I'll create another issue for publishing this on conan center.
