### ISSUE TITLE
Build errors for glibc version greater than 2.26

### ISSUE THREAD

**Issue by dhrvg** [mattiasflodin/reckless#16]
Hi,

SIGUNUSED is synonymous with SIGSYS, and is no longer available since glibc version 2.26 and is causing build errors. I think it can be removed from the signals initializer_list<> in reckless/src/crash_handler.cpp.

Thanks.

**Comment by mattiasflodin** [comment]
Resolved in c1d0932eb884cb2026e7c072f9c2299241b02f6a.
