### ISSUE TITLE
Logging to multiple Files

### ISSUE THREAD

**Issue by aarif4** [mattiasflodin/reckless#24]
Hi,

I'm looking to make a single logger that can log to both stderr and to a file at the same time. Based on my brief inspection of `basic_log`, I realize that I could achieve this by modifying `basic_log` to take in a vector of `writer*` pointers rather than a single pointer.

Is this the "right" way to handle logging to multiple files with this library? Is there a better way?

**Comment by mattiasflodin** [comment]
Hi,

I think the right way to handle this would be to write a new implementation of the writer interface that dispatches to multiple sub-writers. See documentation here: https://github.com/mattiasflodin/reckless/blob/master/doc/manual.md#custom-writers
