### ISSUE TITLE
error build with clang

### ISSUE THREAD

**Issue by JsBlueCat** [mattiasflodin/reckless#39]
we use cmake to build the lib 

```
cmake -DCMAKE_C_COMPILER=clang ../ 
```

and run ```make```

it throws out 

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)  
```

**Comment by mattiasflodin** [comment]
I am unable to reproduce this. Please provide full build output and clang version.

**Comment by mattiasflodin** [comment]
Closing due to no response.
