### ISSUE TITLE
Can reckless output logs to multiple files?

### ISSUE THREAD

**Issue by MagicXran** [mattiasflodin/reckless#44]
I want to classify or customize different event logs to be stored in different files. Does reckless support it?

**Comment by mattiasflodin** [comment]
That depends on what you're after. You could certainly make a variant of severity_log that contains four different instances of policy_log, each of which writes to a different log file depending on the severity level. And you could design something to do whatever arbitrary classification you want. Would that be appropriate for your needs, or could you tell me more about the specific use case and what you had in mind?
